services:
  nginx:
    build: ./srcs/nginx
    depends_on:
      - wordpress
    networks:
      - neet
    ports:
      - "4443:443"
    volumes:
      - wp_files:/var/www/html

  wordpress:
    build: srcs/wordpress
    depends_on:
      - mariadb
    networks:
      - neet
    volumes:
      - wp_files:/var/www/html

  mariadb:
    build: srcs/mariadb
    networks:
      - neet

networks:
  neet:

volumes:
  wp_files:
    driver: local
